X00T: gps: Fix -Wbitwise-instead-of-logical clang warning
error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]

| short-circuit, || don't.
When both arguments to those are boolean,
the short-circuiting version is usually the desired one,
so clang warns on this.

Here, it is inconsequential, so switch to || to suppress the error.

ref: https://gitlab.com/libeigen/eigen/-/commit/b17bcddbca749f621040990a3efb840046315050